export const PLAYLIST_LOADING = 'PLAYLIST_LOADING'
export const PLAYLIST_NEW_REQUEST = 'PLAYLIST_NEW_REQUEST'
export const PLAYLIST_PLAYING_REQUEST = 'PLAYLIST_PLAYING_REQUEST'
export const PLAYLIST_SKIP_REQUEST = 'PLAYLIST_SKIP_REQUEST'
export const PLAYLIST_TRASH_REQUEST = 'PLAYLIST_TRASH_REQUEST'
export const PLAYLIST_END_REQUEST = 'PLAYLIST_END_REQUEST'
export const PLAYLIST_RESPONSE = 'PLAYLIST_RESPONSE'

export const SONG_LYRIC_RESPONSE = 'SONG_LYRIC_RESPONSE'

export const RED_HEART_RATE = 'RED_HEART_RATE'
export const RED_HEART_UNRATE = 'RED_HEART_UNRATE'

export const RECENT_LIST = 'RECENT_LIST'
export const RECENT_EMPTY = 'RECENT_EMPTY'

export const RED_HEART_LIST = 'RED_HEART_LIST'
export const RED_HEART_EMPTY = 'RED_HEART_EMPTY'

export const TRASH_LIST = 'TRASH_LIST'
export const TRASH_EMPTY = 'TRASH_EMPTY'

export const SELECT_PATTERN = 'SELECT_PATTERN'
export const RECENT_PATTERN = 'RECENT_PATTERN'
export const REDHEART_PATTERN = 'REDHEART_PATTERN'
export const SHEET_PATTERN = 'SHEET_PATTERN'
export const DAILY_PATTERN = 'DAILY_PATTERN'

export const SONGLIST_GO = 'SONGLIST_GO'
export const SONGLIST_INDEX_SET = 'SONGLIST_INDEX_SET'
export const SONGLIST_BACK = 'SONGLIST_BACK'

export const APP_CHANNEL = 'APP_CHANNEL'
export const APP_CHANNEL_SET = 'APP_CHANNEL_SET'

export const DAILY_LIST = 'DAILY_LIST'
export const DAILY_EMPTY = 'DAILY_EMPTY'

export const SHEET_SET = 'SHEET_SET'

export const PLAYTIME_SET = 'PLAYTIME_SET'

export const LYRIC_DISPLAY_TRUE = 'LYRIC_DISPLAY_TRUE'
export const LYRIC_DISPLAY_FALSE = 'LYRIC_DISPLAY_FALSE'
