const AUDIO_VOLUME_SET = 'AUDIO_VOLUME_SET'
const OPEN_WITH_PLAYING_SET = 'OPEN_WITH_PLAYING_SET'
const SETTING_SAVE_SUCCESS = 'SETTING_SAVE_SUCCESS'
const SETTING_SAVE_SUCCESS_RESET = 'SETTING_SAVE_SUCCESS_RESET'

export {
  AUDIO_VOLUME_SET,
  SETTING_SAVE_SUCCESS,
  SETTING_SAVE_SUCCESS_RESET,
  OPEN_WITH_PLAYING_SET
}
