const AUDIO_VOLUME_SET = 'AUDIO_VOLUME_SET'
const OPEN_WITH_PLAYING_SET = 'OPEN_WITH_PLAYING_SET'
const RESTORE_LAST_WIN_POS = 'RESTORE_LAST_WIN_POS'
const HIDE_ABOUT = 'HIDE_ABOUT'
const OPEN_PATTERN = 'OPEN_PATTERN'
const COMPACT_STATUS_BAR = 'COMPACT_STATUS_BAR'
const SETTING_SAVE_SUCCESS = 'SETTING_SAVE_SUCCESS'
const SETTING_SAVE_SUCCESS_RESET = 'SETTING_SAVE_SUCCESS_RESET'

export {
  AUDIO_VOLUME_SET,
  OPEN_WITH_PLAYING_SET,
  RESTORE_LAST_WIN_POS,
  HIDE_ABOUT,
  OPEN_PATTERN,
  COMPACT_STATUS_BAR,
  SETTING_SAVE_SUCCESS,
  SETTING_SAVE_SUCCESS_RESET
}
